antfu-collective/vite-plugin-inspect

- src/node/index.ts
This PR fix the plugin not working on windows: the problem is that the browser requests the asset with `<UNIT>:/` and so the browser (at least chrome) detects the request as a file request `file:///<UNIT>:/....`.
To solve the problem, we intercept the `/__inspect_api/resolve` request on the middleware and transform it to return this url `/__resolve_windows/<UNIT>/....` when the server is running on windows and the `id` matches the following pattern `/^([A-Z]+):\/(.*)/`, where the `<UNIT>` is the first capturing group (maybe we can add also lower case `a-z` but I think it is always on upper case and add `+`, I don't remember the max number of units windows can mount).
The first problem is solved, that is, the browser will not fail when fetching the resolved asset:
```ts
// …
```
> fix: plugin not working on windows

- src/node/index.ts
`buildEnd` hook is triggered even if in vite dev server.
Reproduction:
```ts
import { createServer } from 'vite'
createServer().then(async (server) => {
await server.listen()
server.close()
})
```
> fix: don't generate build when dev mode

- src/client/pages/index/module.vue
- src/client/pages/index/plugins-metric.vue
- src/node/index.ts
- src/types.ts
When we are on module page or plugins-metric page, HMR doesn't work. This PR uses `handleHotUpdate` hook to solve that like the way antfu metioned in #8
close #8 
None
> feat: HMR for module page and plugins-metric page

- playground/vite.config.ts
- src/node/index.ts
if config.base is set, the middleware will now be at: "/base-url/__inspect"
fixes #45
> fix: follow vite's base

- src/client/components/DiffEditor.vue
- src/client/logic/codemirror.ts
This PR synchronizes the horizontal scrolling of the two editors:
I think this will make it easier for us to compare codes.
None
None
> feat: synchronized horizontal scrolling in DiffEditor

- src/client/index.html
When accessing `/__inspect` (instead of `/__inspect/`), vite-plugin-inspect shows an empty page.
This is because `sirv` returns the index.html for `/__inspect` but the relative imported paths doesn't work with that path.
This PR adds a code to redirect `/__inspect` to `/__inspect/`.
> feat: redirect when accessed without slash

- playground/package.json
- pnpm-lock.yaml
- src/client/pages/index/module.vue
When unselecting module (navigating from `/__inspect/#/module?id=foo` to `/__inspect/#/`), an error was happening on dev/build.
**dev**
**build**
This PR fixes the error.
Also this PR adds a `build-inspect` command in playground to test out the build inspect feature.
> fix: 404 error when unselecting module

- src/node/index.ts
When vite is configured with [base public path option](https://vitejs.dev/config/shared-options.html#base), the print link to inspect splices the base option twice.
This PR fixes this issue
Fixes https://github.com/antfu/vite-plugin-inspect/issues/56
> fix: inspect entry url is printed incorrectly when vite's base is configured

- src/client/components.d.ts
- src/client/components/SegmentControl.vue
- src/client/logic/state.ts
- src/client/pages/index/plugins-metric.vue
- src/node/index.ts
- src/types.ts
The "plugins metrics" section currently only shows the `transform` metrics. This PR adds the `resolveId` metrics as well.
none
Added this to set up a sort of benchmarking suite for Vite, but I realized it usually doesn't show much info (maybe that's the reason it wasn't implemented), especially during build. I found it was easier to `DEBUG="vite:resolve"` instead 🤔 
Since I already implemented it, I thought to just submit it.
> feat: add resolve id metrics

- src/client/components/ModuleList.vue
i am using this plugin with a more that 2000 modules project, and it always block the UI when searching. So this PR use the virtual list to avoid directly render all the list item.
> perf: use virtual list in module list

- src/client/pages/index/module.vue
Diff content would be latest file when click a new module file, because route query `index` may be undefined, cause `currentIndex` to be NaN. This is related to `vueuse`'s change on `useRouteQuery`, since https://github.com/vueuse/vueuse/pull/2191.
> fix: incorrect diff content in module page

- src/node/index.ts
In some use cases, we want to extend vite-plugin-inspect to enhance certain capabilities. The `silent` option makes sense for it.
Be related to : https://github.com/webfansplz/vite-plugin-vue-devtools/issues/3
> feat: introducting `silent` option

- src/client/pages/index/module.vue
Sometimes `sources` is `[null]` after an SSR transform, the visualizer code expect this field be an array of strings
> fix: handle `[null]` in `sourcemaps.sources` for inspect sourcemaps button

- package.json
- scripts/postbuild.ts
This PR includes:
- add `exports.__esModule=true;` to cjs modules, Vite working (tested with 4.5.0 and 5.0.4: CJS deprecation warning now missing in Vite 5)
- don't remove `d.mts` files, using them in package exports
closes #100 
Downloaded https://stackblitz.com/edit/vitejs-vite-9ncgh5?file=main.js to local and using a local copy of this PR:
Vite 4:
Vite 5:
> fix: default CJS exports

- scripts/postbuild.ts
This PR just use `tsup` approach to define `exports.__esModule` after `use strict` in the postbuild script:
> feat: apply tsup cjs interop

- package.json
- playground/package.json
- playground/src/App.vue
- playground/src/main.ts
- playground/src/router/index.ts
- playground/src/views/Home.vue
- playground/src/views/Other.vue
- pnpm-lock.yaml
- src/client/logic/rpc.ts
- src/node/index.ts
- src/types.ts
This PR is to make module update reactive by rpc functions.
The original issue is [devtools-next #177](https://github.com/vuejs/devtools-next/issues/177). It is expected that after loading lazy-load resources, eg. changing routes with vue-router, the `Graph.vue` should update in real-time which is powered by `vite-plugin-inspect`.
This plugin has a similar problem.
What I do in this PR
- add vue-router in the `playground` to match the repro
- add a simple middleware in vite dev server which is used for checking if some new resources will be loading ( ❗❗❗I'm not sure if it's an appropriate way to do this. )
- add a new `moduleUpdated` rpc function for server and client communication and trigger `refetch` in client-side
Check procedures
- nr dev:client
- cd playground && nr dev
- click the …
> feat: make module update reactive by rpc functions

- src/node/index.ts
This PR removes `console.log` calls and changes logging to use the logger from the resolved Vite config. This way it applies all Vite logger customizations that the developer or framework using Vite did.
https://github.com/lazarv/react-server/issues/10
The `@lazarv/react-server` React meta-framework has a custom logger in place in the Vite configuration and it looks off when `vite-plugin-inspect` is just using `console.log` when printing it's own URLs. Timestamp and prefix configured for the custom logger was not used by this plugin before the changes this PR introduces.
> feat: use vite logger

- src/node/hijack.ts
This PR using internal fix, we can provide options if this another PR merged https://github.com/antfu/error-stack-parser-es/pull/1
closes #115
With this PR, the reproduction in linked issue:
> fix: original error masked when missing stack

- src/client/components/NavBar.vue
- src/client/vite.config.ts
- src/node/context.ts
- src/node/options.ts
- src/types.ts
Issue #123 has been closed and replaced by a new issue for better tracking and clarity.
> feat: `embedded` mode

- build.config.ts
- package.json
- pnpm-lock.yaml
- scripts/postbuild.ts
- src/dir.ts
- src/node/index.ts
Latest released version 0.10.4 is broken, looks like some new dependency moving the plugins to dist/shared folder and so the DIR_CLIENT is wrong (previous versions the plugins were on dist folder).
This PR also includes:
- fixes broken types, now we only need to fix nuxt.cjs (replace `exports.default = nuxt` with `exports = nuxt`)
- adds unbuild `build:done` hook to check the client directory exists from both CJS and ESM modules: exported `DIR_CLIENT` from the plugin to allow check it
- adds `@arethetypeswrong/cli` to check types are not broken, running after patching nuxt.cjs in build script
Without this PR (https://arethetypeswrong.github.io/?p=vite-plugin-inspect%400.10.4):
With this PR:
resolves #125
resolves #126
resolves #129
supersedes #127
> fix: broken 0.10.4 version

- build.config.ts
- scripts/postbuild.ts
- src/dirs.ts
- src/node/build.ts
- src/node/index.ts
This to make sure the logic in `dirs.ts` always be bundled as `dist/dirs.ts`
> build: create entry for `dirs` to stabilize path resolve

- src/client/worker/diff.worker.ts
Currently the diff breaks when one side has CRLF and the other side LF line endings. This PR adds a small replace to the diff worker to fix the positioning.
Before:
After:
A different approach would be to set the CodeMirror instances to the correct line endings, but then there is the problem that each line ending is marked as a change in diff.
If in the future more stuff is added to the code editor this could be reconsidered, but for now only replacing when the diff is requested seems fine to me.
> fix: diff positioning with CRLF

- package.json
- pnpm-lock.yaml
- src/node/index.ts
- src/node/preview.ts
Hello @antfu,
This PR replaces `picocolors` with a better alternative `ansis` that supports both CJS and ESM.
Ansis supports chained syntax for clean and readable code.
Ansis is nearly as small (6.8 kB) as Picocolors (6.4 kB).
> feat: replace picocolors with ansis

- build.config.ts
- src/node/build.ts
- Added `force` option for `fs.rm` call to ignore `ENOENT` exception.
- Lint issue for extra space.
- Lint issue for string concat.
#141 
- https://nodejs.org/api/fs.html#fspromisesrmpath-options
> fix: rm `outputDir` with `force` option to ignore ENOENT exception

- package.json
- scripts/postbuild.ts
We're patching `.cjs` files and we must patch `d.ts` and `d.cts` files, there is an extra `default.default` when resolving the inspect plugin in the vite config file (check the screenshot in the linked issue).
I'm going to try to fix it at `unbuild` ASAP, I need to create the repository and publish initial version, I guess this weekend should be fixed 🤞 .
This PR also updates pnpm to `v10.4.0`.
closes #143
> fix(cjs): wrong cjs default exports

- src/client/components/DiffEditor.vue
- src/client/pages/index/module.vue
- src/client/styles/main.css
When the state is oneColumn, the splitpanes__splitter is not hidden.
The default min-width of splitpanes__splitter is 1px, so it cannot be set to 0.
Use splitpanes__splitter as a border to optimize the style.
> chore(client): Optimize the splitpanes style

- src/node/build.ts
- src/node/index.ts
This PR adds a multi-environment support for build.
Without this PR, only the last report for the last environment was output, because the report generation for each environment deletes the previous reports.
I tested this PR with `examples/vue-ssr` in https://github.com/hi-ogawa/vite-environment-examples.
> feat: add multi-env support for build

- src/node/build.ts
- src/node/context.ts
- src/node/index.ts
~~**This PR is built on top of #148**~~
This PR makes the module graph view work for build.
This is achieved by using `pluginCtx.getModuleInfo(id)` as an replacement of `moduleGraph?.getModuleById(id)`.
I tested this PR with `examples/vue-ssr` in https://github.com/hi-ogawa/vite-environment-examples.
> feat: generate module relationship for build

- src/node/index.ts
I was testing my own plugin with Vite 7 beta override (https://github.com/hi-ogawa/vite-plugins/pull/944) and noticed `vite-plugin-inspect`'s `hotUpdate` is causing an error, which was used in one of my test case.
```
Cannot read properties of undefined (reading 'hot')
at MinimalPluginContext.hotUpdate (file:///home/hiroshi/code/personal/vite-plugins/node_modules/.pnpm/vite-plugin-inspect@11.0.1_vite@7.0.0-beta.1_@types+node@22.14.1_jiti@2.4.2_lightningcs_b960494e74fe6a7fc89f3caa40fce88e/node_modules/vite-plugin-inspect/dist/shared/vite-plugin-inspect.Bht9Q8w0.mjs:681:19)
```
`hotUpdate({ environment })` is deprecated all along during Vite 6 and `hotUpdate() { this.environment }` has been a stable alternative. See https://github.com/vitejs/vite/pull/19986 for the detail.
> fix: use `this.environment` in `hotUpdate` for Vite 7 compatibility

- src/node/build.ts
- src/node/index.ts
At build time, each environment has its own config (unless `builder.sharedConfigBuild: true` is used), so they are treated as multiple Vite instances (this is the behavior of #148 when it's working). 
However, #148 writes `reports/metadata.json` after the first environment finishes building. In small projects, the second environment might be able to start building and register itself to `InspectContext`, while this plugin prepares its output folder and copies frontend files, to be included in the `reports/metadata.json` file.
But for larger projects, there are many works to do after the `buildEnd` Vite plugin hook, like writing bundled files to output folder, or other plugin hooks, so the second environment can't start in time.
This PR delays writing metadata file after all environments …
> fix: generate metadata for all environments for build

- src/client/App.vue
- src/client/components/Container.vue
The `main` box and `Container` component are using `h-screen` to calculate the height of page, but `h-screen` will includes the horizontal scrollbar, so the unexpected vertical scrollbar will be also displayed if the screen is narrow, and `h-full` is not including the scrollbar, so it can fix it. 
N/A
> fix: remove unexpected scrollbar on the narrow screen

- pnpm-lock.yaml
- pnpm-workspace.yaml
I'm not sure this dependency change was intended in v11.0.1, but based on the commit title it seems like it was meant to be temporary 🤔 https://github.com/antfu-collective/vite-plugin-inspect/commit/8bbf546b77aa01232fbcf124caf72c8f2a28139a
This resolves https://github.com/nuxt/devtools/issues/887
* https://github.com/nuxt/devtools/issues/887
> fix: replace `rolldown-vite` with `vite`
